name: clean_arc_tdd_course
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^2.0.1                # Service locator.
  flutter_bloc: ^0.21.0         # Bloc for state management
  equatable: ^0.4.0             # Value equality
  dartz: ^0.8.6                 # Functional programming thingies
  connectivity: ^0.4.3+7        # Remote API
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4  # Local cache

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

flutter:
  uses-material-design: true
